#! /bin/bash
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
wget https://github.com/kubernetes/kops/releases/download/v1.25.0/kops-linux-amd64
chmod +x kops-linux-amd64 kubectl
mv kubectl /usr/local/bin/kubectl
mv kops-linux-amd64 /usr/local/bin/kops

export KOPS_STATE_STORE=s3://gopi.flm.k8s
kops create cluster --name sai.k8s.local --zones us-east-1a,us-east-1b,us-east-1c --control-plane-size t2.medium --control-plane-count 1 --control-plane-volume-size 30 --node-size t2.micro --node-count 2 --node-volume-size 20
kops update cluster --name sai.k8s.local --yes --admin
