---
appVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: swiggy
 spec:
   containers: 
     - name: cont-1
        image: shaikmustafa/dm
        ports:
          - containerPort: 80
    
