apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  # Key-value pairs
  APP_NAME: "MyApp"
  APP_ENV: "development"
  DATABASE_URL: "http://dev-database.example.com"

  # Multi-line configuration stored as a key-value pair
  APP_PROPERTIES: |
    server.port=8080
    server.address=0.0.0.0
    spring.datasource.url=jdbc:mysql://db:3306/mydb
    spring.datasource.username=root
