apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: cont-1
      image: nginx
      env:
        # Reference a single key from the ConfigMap
        - name: value1
          valueFrom:
            configMapKeyRef:
              name: my-cm # Name of the ConfigMap-1
              key: APP_ENV       # Specific key to attach
        - name: value2
          valueFrom:
            configMapKeyRef:
              name: configmap-2 # Name of the ConfigMap-2
              key: APP_NAME # Specific key to attach
