apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: cont-1
      image: nginx
      - name: value1
          valueFrom:
            secretKeyRef:
              name: my-secret # Name of the Secret-1
              key: username # Specific key to attach
      - name: value1
          valueFrom:
            secretKeyRef:
              name: new-secret # Name of the Secret-1
              key: password # Specific key to attach
