apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: cont-1
      image: nginx
      env:
        # Reference a single key from the ConfigMap
        - name: value1
          valueFrom:
            secretKeyRef:
              name: user # Name of the ConfigMap
              key: username # Specific key to attach
