apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: cont-1
      image: nginx
      volumes:
          - name: my-volume
            configMap:
              name: my-cm

  volumeMounts:
  - name: my-volume
    mountPath: /etc/config
